save Run_Ex/O2oall.txt O2oall -ascii
save Run_Ex/O2all.txt O2all -ascii
save Run_Ex/Sdall.txt Sdall -ascii
save Run_Ex/Sall.txt Sall -ascii
save Run_Ex/NH4all.txt NH4all -ascii
save Run_Ex/NO2all.txt NO2all -ascii
save Run_Ex/NO3all.txt NO3all -ascii
save Run_Ex/N2all.txt N2all -ascii
save Run_Ex/XQoall.txt XQoall -ascii
save Run_Ex/XQoPall.txt XQoPall -ascii
save Run_Ex/XQn1all.txt XQn1all -ascii
save Run_Ex/XQn1Pall.txt XQn1Pall -ascii
save Run_Ex/XQn23all.txt XQn23all -ascii
save Run_Ex/XQn23Pall.txt XQn23Pall -ascii
save Run_Ex/XQn123all.txt XQn123all -ascii
save Run_Ex/XQbnh4all.txt XQbnh4all -ascii
save Run_Ex/XQbno2all.txt XQbno2all -ascii
save Run_Ex/XQaall.txt XQaall -ascii
save Run_Ex/XQaniall.txt XQaniall -ascii
save Run_Ex/XQfacall.txt XQfacall -ascii
save Run_Ex/facaerall.txt facaerall -ascii